[package]
name = "jito-protos"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
tonic-prost="0.14"
prost = "0.14"
prost-types = "0.14"
tonic = "0.14"

[build-dependencies]
tonic-prost-build = "0.14"
protobuf-src = "1"

